kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: crcw-webhook-alertmanager
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'quay.io/fdavalo/crcw-webhook-alertmanager:latest'
    pushSecret:
      name: fdavalo-fdavalo-robot-pull-secret
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:14-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/fdavalo/crcw-webhook-alertmanager'
  runPolicy: Serial
